version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
<<<<<<< HEAD
    allowed_updates:
      - match:
        dependency_name: "textlint"
=======
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
>>>>>>> 8af62c6ee14d6c5e00d4041aeaf7de234f5e3169
